name:                aoc2021
version:             0.1.0.0
github:              "typesafety/aoc2021"
license:             BSD3
author:              "Thomas Li"
maintainer:          "ailoodee@gmail.com"
copyright:           "2021 Thomas Li"

extra-source-files:
- README.md
description:         Solutions for Advent of Code 2021

dependencies:
- base >= 4.7 && < 5

- containers
- microlens-platform
- polysemy
- polysemy-plugin
- relude
- text
- time
- unordered-containers

library:
  source-dirs: src
  exposed-modules:
    - CustomPrelude

    - DayPart
    - Solutions.Day1
    - Solutions.Day2
    - Solutions.Day3

executables:
  aoc2021-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O1
    dependencies:
    - aoc2021
    when:
    - condition: false
      other-modules: Paths_aoc2021

tests:
  aoc2021-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021
    - hspec

default-extensions:
- NoImplicitPrelude

- DataKinds
- DerivingVia
- FlexibleContexts
- GADTs
- ImportQualifiedPost
- LambdaCase
- MultiWayIf
- OverloadedLabels
- OverloadedLists
- OverloadedStrings
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeOperators
- UnboxedTuples
- ViewPatterns

ghc-options:
# Warnings
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wpartial-fields
- -Wredundant-constraints

# Exceptions
- -Wno-missing-export-lists

# Plugin for better Polysemy type inference
- -fplugin=Polysemy.Plugin
